# Generated by Django 5.0.4 on 2024-04-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_slug_alter_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='apply/')),
                ('cover_letter', models.TextField(max_length=700)),
            ],
        ),
    ]
