# Generated by Django 5.0.4 on 2024-04-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
