# Generated by Django 5.0.4 on 2024-04-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='web_site',
            field=models.URLField(null=True),
        ),
    ]
